version: 2

sources:
  - name: raw
    database: DEMO_DB
    schema: RAW

    tables:
      - name: customers

        columns:
          - name: customer_id
            data_tests:
              - not_null
              - unique

          - name: customer_name
            data_tests:
              - not_null

      - name: customer_incremental